#
###################################
# Site wide configuration
####################################
#
title: Victor Zhu
email: me@zhuzhuuu.com
description: Heyy you have found me (*•̀ᴗ•́*)و.
url: https://zhuzhuuu.com # the base hostname & protocol for your site
keywords: ["Victor Zhu", "Programming", "Cybersecurity", "Software Engineering", "slinv"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:categories/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Victor Zhu
  avatar: zhu-yinke-300x300.png
  job: "Student & Software Engineer"
  bio: "A Computer Science Student @ Rensselaer Polytechnic Institute who is intrigued by Cybersecurity. Favorite sport: Hack."
  email: me@zhuzhuuu.com
  protonmail: victor.zhu@protonmail.com
  disqus-shortname: zhuzhuuu
  twitter: zzy809 #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-93013663-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: SLiNv #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: zhuzhuuu #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: slinvic #username

plugins:
  - jekyll-gist
  - jemoji
