title:            Victor · Blog
description:      Heyy you have found me (*•̀ᴗ•́*)و
logo:             theme-img/zhu-yinke-300x300.png
disqus_shortname: zhuzhuuu
duoshuo_shortname: 

# Assign a default image for your site's header and footer
default_bg:       wj/4.jpg
default_bg_size:  15
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Specify the average Words per minute. If not defined, 180 will be used
wpm:				      80
# Turn on or off the fin animations in the header and footer
triangleheader:		true
animated_fins:	  true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
port:             4000
host:             127.0.0.1
#baseurl:          ""

# Added features
features:
    random_background:   true
    star_me_on_github: true

# Owner/author information
owner:
  name:           Victor Zhu
  avatar:         theme-img/zhu.png
  email:          me@zhuzhuuu.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Comp Sci Student @ Rensselaer Polytechnic Institute
  # Social networking links used in footer. Update and remove as you like.
  facebook:       
  twitter:        
  github:         slinv
  stackexchange:
  linkedin:       http://www.linkedin.com/in/zhuzhuuu
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-93013663-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home | 主页
    url: /
    external: false
    icon: home
  - title: Categories | 归档
    url: /categories
    icon: list
  - title: Guestbook | 留言板
    url: /guestbook
    icon: comment
  # - title: <i class="icon-tags"></i> 标签
  #   url: /tags
  - title: 个人收藏
    url: /favourite
    icon: heart
  - title: About me | 关于我
    url: /about-me
    icon: user

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

#excerpt_separator: "<!--more-->"

# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink:   /:categories/:title
permalink: /:categories/:year/:month/:day/:title.html


kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6


sass:
  style: compressed

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

gems: ['jekyll-paginate', 'jekyll/tagging', 'jekyll-tagging-related_posts']
languages: ['en', 'cn']
language_default: 'cn'

# page features:
# - page specific assets -> http://mattgemmell.com/page-specific-assets-with-jekyll/
# - MathJax -> 